### ISSUE TITLE
Bottom menu different from top menu

### ISSUE THREAD

**Issue by MichaelCurrie** [openworm/org.openworm.website#92]
The bottom menu:

    Blog · About · FAQ · People · Events · Media · Projects · Publications · Milestones & Issues · Roadmap · Contacts

The top menu:

- Home
- Get Started
- Get Involved
- Downloads
- Supporters
- Media
- Science
- Donate
- Explore the Worm

**Comment by gidili** [comment]
@MichaelCurrie this is on purpose and pretty standard on just any website. You can fit more stuff on the bottom menu and on the top menu we initially put only what was seen at the time  as "the most important stuff". Also this is because as soon as it doesnt fit in one line it will transition to mobile/tabled layout and you wont see the menu at the top at all but just a button on the right. The perception might have changed of what we want up there in the top menu but I dont think it should reflect what's on the bottom menu which is a bucket for pretty much everything else.

**Comment by MichaelCurrie** [comment]
OK.
